char pmu[36][1000] =
{"1. Omowic proces implantacji pigmentu w skorze",
"2. Etapy pigmentacji skory. Po jakim czasie powinna nastapic pigmentacja dopełniajaca (II zabieg). Prosze uzasadnic odpowiedz.",
"3. Jak wyglada proces gojenia w skorze poddanej pigmentacji? Prosze wymienic poszczegolne etapy gojenia. ",
"4. W ktorej warstwie skory powinien zostac osadzony pigment. Prosze uzasadnic odpowiedz.",
"5. Co dzieje sie z pigmentem w skorze w dłuzszym odstepie czasowym (po roku, kilku latach i wiecej).",
"6. Ogolne przeciwskazania do pigmentacji skory. ",
"7. Przeciwskazania do pigmentacji ust. ",
"8. Przeciwskazania do pigmentacji powiek",
"9. Przeciwskazania do pigmentacji brwi",
"10. Ogolne wskazania do wykonania makijazu permanentnego.",
"11. Ogolne zasady pielegnacji miejsc pigmentowanych: makijaz permanentny i tatuaz.",
"12. Pielegnacja i wskazania po wykonaniu pigmentacji ust.",
"13. Pielegnacja i wskazania po wykonaniu pigmentacji powiek.",
"14. Pielegnacja i wskazania po wykonaniu pigmentacji brwi. ",
"15. Omowic problem migracji pigmentu w skorze. Czym moze byc spowodowana migracja? ",
"16. Co jest przyczyna odbarwienia pigmentu w skorze. Prosze wymienic przynajmniej trzy przyczyny.",
"17. Omowic mozliwe skutki niepozadane po pigmentacji.",
"18. Omowic wpływ opalania sie na pigmentacje.",
"19. Omowic wpływ stosowania odzywek do rzes na proces pigmentacji.",
"20. Jakie czynniki wpływaja na upośledzenie procesu gojenia w makijazu permanentnym i tatuazach.",
"21. Jakie ryzyko niesie powiklanie gojenia skory w makijazu permanentnym i tatuazach.",
"22. Pigmentacja skory zmienionej - prosze omowic zasady bezpieczenstwa (brodawki, piegi, znamiona).",
"23. Wystepowanie keloidow - ryzyka zwiazane z pigmentacja.",
"24. Pigmentacja medyczna. Zastosowanie pigmentacji medycznej w problemach estetycznych.",
"25. Pigmentacja medyczna. Omowic mozliwosci pigmentacji u osob z chorobami onkologicznymi.",
"26. Jaki jest podstawowy sklad tuszy stosowanych w makijazu permanentnym i tatuazach.",
"27. Tlenek tytanu i jego wplyw na dobor metody usuwania pigmentacji.",
"28. Metody usuwania makijazu permanentnego i tatuazy. Laseroterapia: scharakteryzowac na czym polega ta metoda i ocenic jej skutecznosc. ",
"29. Zastosowanie laseroterapii: rodzaje laserow i długosc fal wykorzystywanych w usuwaniu pigmentacji. ",
"30. Metody usuwania makijazu permanentnego i tatuazy. Removery: scharakteryzowac na czym polega ta metoda i ocenic jej skutecznosc. ",
"31. Alternatywne metody usuwania makijazu permanentnego i tatuazu. Prosze stosowania. ",
"32. W jaki sposob mozna zneutralizowac odbarwienia w makijazu permanentnym w kolorach: czerwonym, fioletowym, zielonym, niebieskim.",
"33. Kolo barw - budowa i zastosowanie w kosmetologii, w tym w pigmentacji skory.",
"34. Kolorymetria: podzial barw.",
"35. Fototypy skory wedlug klasyfikacji Fitzpatrick.",
"36. Wykorzystanie klasyfikacji Fitzpatrick w kosmetologii i makijazu permanentnym."
};

char aa[36][1000]=
{
"1. Wymien orientalne techniki relaksacyjne i omow jedna z nich. ",
"2. Na czym polega koloroterapia? Prosze wymienic wlasciwosci kilku kolorow.",
"3. Wymien rodzaje masazu i omow jego wplyw na organizm czlowieka. ",
"4. Wymien metody aparaturowe zwiazane ze stymulacja tkanek i omow na czym polegaja.",
"5. Wymien rodzaje zabiegow z zakresu medycyny uzdrowiskowej i medycyny fizykalnej oraz omow jeden z nich.",
"6. Zdefiniuj termin peloidy. Na czym polega terapia z wykorzystaniem peloidow.",
"7. Jakie sa zalety terapii z wykorzystaniem borowiny? Podaj przyklady zabiegow. Wymien przeciwwskazania.",
"8. Co to jest talasoterapia. Podaj przyklady zabiegow. Wymien przeciwwskazania.",
"9. Co to jest balneologia. Podaj przykłady zabiegow. Wymien przeciwwskazania",
"10. Jaki wplyw ma masaz na tkanki organizmu? Wymien przeciwwskazania.",
"11. Drenaz limfatyczny - na czym polega i kto moze z niego skorzystac?",
"12. Scharakteryzuj rodzaje cwiczen relaksacyjnych stosowanych w odnowie biologicznej.",
"13. Jaki wplyw na organizm ma masaz goracymi kamieniami wulkanicznymi? Wymien przeciwwskazania.",
"14. Scharakteryzuj pojecie termoterapia, podaj przyklady zabiegow stosowanych w odnowie biologicznej. ",
"15. Na czy polega idea holistycznego podejscia do pacjenta w odnowie biologicznej?",
"16. Na czym polega aromaterapia i jaki ma wplyw na organizm? Wymien przeciwwskazania do stosowania aromaterapii.",
"17. Wyjasnij mechanizm dzialania zabiegu mikronakluwania skory.",
"18. Wskazania do mezoterapii mikroiglowej.",
"19. Mezoterapia mikroiglowa - zasady wykonania zabiegu.",
"20. Jakie urzadzenia sa wykorzystywane do wykonania zabiegu mikronakluwania skory.",
"21. Omow mozliwości łaczenia mikronakłuwania z innymi zabiegami.",
"22. Opisz czynniki aktywne, ktore w najwiekszym stopniu przyczynia sie do poprawy efektywności zabiegu mikronakłuwania skory.",
"23. Omow wskazania i przeciwwskazania do wykonania zabiegu mikronakluwania.",
"24. Wyjasnij mechanizm dzialania mezoterapii beziglowej.",
"25. Wyjasnij na czym polega zjawisko elektroporacji",
"26. Omow wskazania i przeciwwskazania do zabiegu mezoterapii beziglowej",
"27. Omow dzialanie kwasu glikolowego",
"28. Omow dzialanie peelingow chemicznych stosowanych w terapii przeciwstarzeniowej.",
"29. Zastosowanie i rola witaminy C w zabiegach pielegnacyjnych.",
"30. Wymien procedury niezbednie do bezpiecznego wykonania zabiegu z przerwaniem ciaglosci naskorka.",
"31. Czynniki zewnetrzne warunkujace mechanizmy starzenia twarzy",
"32. Czynniki wewnetrzne warunkujace mechanizmy starzenia twarzy",
"33. Jakie zabiegi wykorzystywane sa w biorewitalizacji. Omow wybrany",
"34. Techniki manualne wykorzystywane w terapii przeciwstarzeniowej",
"35. Omow najskuteczniejsze skladniki aktywne wykorzystywane w terapii przeciwstarzeniowej.",
"36. Wykorzystanie witaminy A w zabiegach przeciwstarzeniowych",
};

char ogl[84][1000]=
{
    "1. Jak sie ocenia bezpieczenstwo kosmetykow?",
    "2. Co to sa surowce kosmetyczne? Podzial surowcow ze wzgledu na funkcje w preparacie.",
    "3. Co to sa formulacje produktow kosmetycznych?",
    "4. Prosze omowic funkcje emolientow w kosmetyce pielegnacyjnej oraz podac przyklady surowcow, pelniacych powyzsze funkcje",
    "5. Jakie sa metody pozyskiwania olejkow eterycznych?",
    "6. Jakie zwiazki chemiczne moga miec won roznych kwiatow i migdalow?",
    "7. Prosze wymienic surowce zapachowe – naturalne, pochodzenia zwierzecego i roslinnego oraz opisac jeden z nich.",
    "8. Co to znaczy INCI? Wedlug jakich zasad jest tworzone?",
    "9. Jakie czynniki wplywaja na transdermalna przenikalnosc substancji aktywnych zawartych w preparatach kosmetycznych?",
    "10. Prosze wyjasnic pojecie pH omowic skale i podac definicje",
    "11. Jakie sa zasady tworzenia kompozycji zapachowych?",
    "12. Emulsje wielokrotne - co to jest i jaka pelnia role.",
    "13. Wymien rodzaje filtrow przeciw promieniowaniu UV wykorzystywanych w preparatach kosmetycznych.",
    "14. Co to jest: ambra, pizmo, kastoreum? Jakie zastosowanie znajduja w przemysle Kosmetycznym",
    "15. Jakie sa wskazania do terapii glikokortykosterydowej.",
    "16. Jakie grupy lekow sa stosowane w leczeniu ogolnym tradziku. Scharakteryzuj jedna z nich.",
    "17. Wymien substancje czynne o silnym dzialaniu przeciwrodnikowym i majace zdolnosc neutralizacji tlenu singletowego.",
    "18. Jakie preparaty i substancje aktywne znajduja zastosowanie w leczeniu oparzen i odmrozen skory.",
    "19. Wymien i omow preparaty do odkazania i przemywania ran i odlezyn .",
    "20. Wymien przeciwwirusowe leki do stosowania miejscowego.",
    "21. Jakie dzialaniem charakteryzuje sie aspiryna. Jakie sa przeciwwskazania do stosowania aspiryny.",
    "22. Jakie moga byc skutki uboczne stosowania retinoidow.",
    "23. Jakie znasz produkty naturalne stosowane w srodkach odchudzajacych. Omow dzialanie dwoch z nich.",
    "24. Jakie zastosowanie w leczeniu miejscowym znajduje siarka stracona i siarka sublimowana",
    "25. Jakie antybiotyki najczesciej znajduja zastosowanie w leczeniu chorob dermatologicznych.",
    "26. Co to jest ichtiol i jakie ma dzialanie.",
    "27. Jakie dzialanie lecznicze maja zwiazki srebra, stosowane miejscowo.",
    "28. Czym sa retinoidy naturalne. Podaj przyklady.",
    "29. Czym sa naturalne adaptageny i jakie maja dzialanie.",
    "30. Jakie sa przeciwwskazania do stosowania Niesteroidowych Lekow Przeciwzapalnych?",
    "31. Jakie sa skutki uboczne stosowania glikokortykosterydow",
    "32. Wymien glowne grupy substancji aktywnych w preparatach dezynfekcyjnych.",
    "33. Omow aktywnosc przeciwdrobnoustrojowa aldehydow",
    "34. Ekstrakty roslinne (pozyskiwanie, rodzaje, mozliwosci wykorzystania).",
    "35. Oleje roslinne w kosmetyce – pozyskiwanie, podzial, mozliwosci wykorzystania.",
    "36. Roslinne substancje biologicznie czynne i ich dzialanie kosmetyczne.",
    "37. Wykorzystanie olejkow eterycznych w produktach kosmetycznych",
    "38. Konserwanty w preparatach kosmetycznych (podzial, znaczenie, przyklady).",
    "39. Substancje pomocnicze stosowane w kosmetykach (znaczenie, przyklady)",
    "40. Nosicielstwo drobnoustrojow (definicja, rodzaje, przyklad). ",
    "41. Dezynfekcja i sterylizacja w gabinecie kosmetologicznym.",
    "42. Czynniki wplywajace na kontaminacje produktow kosmetycznych.",
    "43. Czynniki etiologiczne bakteryjnych zakazen skory (ropnych i nieropnych).",
    "44. Wirusy przenoszone przez krew (charakterystyka, postepowanie po ekspozycji)",
    "45. Mikroflora fizjologiczna czlowieka (charakterystyka, podzial, znaczenie).",
    "46. Zagrozenia mikrobiologiczne w gabinecie kosmetologicznym",
    "47. Budowa oraz funkcje bialek. Wykorzystywanie bialek w kosmetologii",
    "48. Enzymy - ich dzialanie i zastosowanie w kosmetologii.",
    "49. Wykorzystanie mikro- i makroelementow w kosmetyce.",
    "50. Witaminy – ich podzial i zastosowanie w kosmetologii.",
    "51. Wplyw diety na skore i jej przydatki.",
    "52. Miesnie mimiczne twarzy - charakterystyka (budowa, podzial i funkcja)",
    "53. Miesnie szyi – charakterystyka, podzial i ich czynnosci",
    "54. Kosci czaszki",
    "55. Miesnie agonistyczne i antagonistyczne (definicja i przyklady).",
    "56. Rdzen kregowy – budowa i funkcje.",
    "57. Czynnosci ukladu nerwowego osrodkowego",
    "58. Uklad nerwowy obwodowy – budowa i funkcja",
    "59. Budowa i funkcje skory",
    "60. Charakterystyka przydatkow skory",
    "61. Wyjasnij co to jest „pKa”",
    "62. Wyjasnij jak pH wplywa na moc roztworu substancji kwasowej",
    "63. Wyjasnij od czego zalezy moc preparatu kwasowego",
    "64. Wymien peelingi chemiczne wykorzystywane w terapii tradziku pospolitego. Opisz ich dzialanie",
    "65. Omow bezwzgledne przeciwwskazania do zluszczan chemicznych",
    "66. Omow dzialanie i zastosowanie kwasu azelainowego",
    "67. Wymien i scharakteryzuj skladniki aktywne wykorzystywane w terapii skor naczyniowych",
    "68. Jakie skladniki aktywne moga byc skutecznie wykorzystane w terapii cellulitu",
    "69. Prosze wskazac prawidlowa kolejnosc czynnosci w masazu klasycznym – omow jakiemu celowi sluzy kazda z nich.",
    "70. Omow wlasciwosci ultradzwiekow oraz ich oddzialywanie na tkanki.",
    "71. Co to jest zjawisko kawitacji, opisz kawitacje stabilna i niestabilna oraz ich wplyw na organizm czlowieka.",
    "72. Opisz zasady przeprowadzania naswietlen promieniowaniem podczerwonym (IR).",
    "73. Scharakteryzuj promieniowania UVA i UVB oraz jego wplyw na organizm.",
    "74. Co to jest lampa BIOPTRON – podaj wskazania i przeciwskazania do naswietlania",
    "75. Co to jest lampa SOLLUX – podaj wskazania i przeciwskazania do naswietlania i dzialanie na skore przy naswietlaniu filtrem czerwonym i niebieskim.",
    "76. Co to jest elektrostymulacja. Opisz biologiczny wplyw na organizm czlowieka.",
    "77. Omow dzialanie pradow d’Arsonvala. Podaj wskazania i przeciwskazania do ich zastosowania.",
    "78. Podaj wskazania i przeciwskazania do laseroterapii",
    "79. Opisz lampy IPL oraz podaj wskazania i przeciwskazania do zabiegu",
    "80. Opisz mechanizm oddzialywania ciepla na organizm czlowieka. Podaj wskazania i przeciwskazania do zabiegu cieplolecznictwa.",
    "81. Opisz mechanizm oddzialywania zimna na organizm czlowieka. Podaj wskazania i przeciwskazania do zabiegu krioterapii",
    "82. Wyjasnij na czym polega zabieg galwanizacji. Opisz dzialanie anody i katody w zabiegu galwanizacji.",
    "83. Wyjasnij na czym polega zabieg jonoforezy oraz jakie czynniki wplywaja na skutecznosc jonoforezy.",
    "84. Opisz cechy rumienia fotochemicznego oraz jego wplyw na organizm",
};
